---
- name: Install packages
  ansible.builtin.dnf:
    name: ipa-server
    state: present

- name: Clear hosts file
  ansible.builtin.file:
    path: /etc/hosts
    state: absent
    force: true

- name: Make hosts file
  ansible.builtin.file:
    path: /etc/hosts
    state: touch
    force: true

- name: Configure hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ ip }}	{{ fqdn }} {{ hostname }}"

- name: Corrige hosts file in boot
  ansible.builtin.lineinfile:
    path: /etc/rc.local
    state: present
    line: "{{ item }}"
  loop:
    - sed -i "/127.0.0.1/,/localhost6;/d" /etc/hosts
    - echo "{{ ip }}	{{ fqdn }} {{ hostname }}" >> /etc/hosts

- name: Enable rc.local
  ansible.builtin.command: chmod +x /etc/rc.local

- name: Install IPA Server
  ansible.builtin.command: "ipa-server-install --ds-password={{ password }} --admin-password={{ password }} --ip-address={{ ip }} --domain={{ domain }} --realm={{ domain }} --hostname={{ fqdn }} --skip-mem-check -U"