---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install subscription-manager
  ansible.builtin.dnf:
    name: subscription-manager
    state: present

- name: Install server certification
  ansible.builtin.shell: "rpm -Uvh http://{{ foreman_server }}/pub/katello-ca-consumer-latest.noarch.rpm"
  args:
    executable: /bin/bash
  when: "'katello-ca-consumer-{{ foreman_server }}' not in ansible_facts.packages"
        
- name: Get default organization
  theforeman.foreman.organization_info:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "http://{{ foreman_server }}"
  register: orgs

- name: Register with activationkey 
  community.general.redhat_subscription:
    state: present
    activationkey: "HML_RCEL9"
    org_id: "{{ orgs.organizations[0].label }}"
    server_hostname: "{{ foreman_server }}"
    rhsm_baseurl: "http://{{ foreman_server }}/pulp/repos"
    force_register: true
    
- name: Gather default repositories
  ansible.builtin.shell: "yum repolist enabled | egrep -v '{{ orgs.organizations[0].label }}|repo' | awk '{print $1}' | xargs"
  args:
    executable: /bin/bash
  register: default_repositories

- name: Disable default repositories
  ansible.builtin.shell: "yum-config-manager --disable {{ default_repositories.stdout }}"
  args:
    executable: /bin/bash