---
- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Copy container-pihole.service
  ansible.builtin.copy:
    src: ../files/container-pihole.service
    dest: /etc/systemd/system/container-pihole.service
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Replace the config container service
  ansible.builtin.replace:
    path: /etc/systemd/system/container-pihole.service
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  loop:
    - { regex: "timezone_change", replace: "{{ timezone }}" }
    - { regex: "password_change", replace: "{{ password }}" }
    - { regex: "dns_change", replace: "{{ dns }}" }
    - { regex: "fqdn_change", replace: "{{ fqdn }}" }

- name: Create volumes paths
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    force: true
  loop:
    - "/home/edge/pihole/etc-pihole"
    - "/home/edge/pihole/etc-dnsmasq.d"

- name: Permit traffic in default zone on port 53/udp
  ansible.posix.firewalld:
    port: 53/udp
    permanent: true
    state: enabled
  ignore_errors: true

- name: Permit traffic in default zone on service http(s)
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - https

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: Start service container-pihole
  ansible.builtin.systemd_service:
    name: container-pihole
    enabled: true
    state: started
    daemon_reload: true
  retries: 3
  delay: 5