---
- name: Set timezone
  ansible.builtin.command: "timedatectl set-timezone {{ timezone }}"

- name: Verify if cloud-init started update packages
  ansible.builtin.command: "pgrep -f '(yum|dnf)'"
  register: yum_dnf_process
  until: yum_dnf_process.rc != 0
  retries: 20
  delay: 30
  ignore_errors: true

- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes
  ignore_errors: true