---
- name: Wait startup Servers
  become: true
  hosts: localhost
  roles: 
    - initial

- name: Setup internal DNS server
  become: true
  hosts: domain
  roles: 
    - domain

- name: Update packages and timezone
  become: true
  hosts: servers
  roles:
    - common

- name: Setup PI-Hole server
  become: true
  hosts: pihole
  roles:
    - pihole

- name: Setup IDM server
  become: true
  hosts: idm
  roles:
    - idm

- name: Setup AWX server
  become: true
  hosts: awx
  roles:
    - awx

- name: Setup Gitlab server
  become: true
  hosts: gitlab
  roles:
    - gitlab

- name: Setup Rundeck server
  become: true
  hosts: rundeck
  roles:
    - rundeck

- name: Setup Foreman server
  become: true
  hosts: foreman
  roles:
    - foreman

- name: Setup admx
  become: true
  hosts: admx
  roles:
    - admx

- name: Register Foreman
  become: true
  hosts: subscription
  roles:
    - subscription