---
- name: Install dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - policycoreutils 
    - perl
    - openssh-server

- name: Permit HTTPS/HTTP traffic
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    zone: public
    state: enabled
  loop:
    - http
    - https
    - ssh
  ignore_errors: true

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: Install postfix
  ansible.builtin.dnf:
    name: postfix
    state: present

- name: Start and enabled postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Install Repositorie Gitlab CE
  ansible.builtin.shell:
    cmd: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | bash
    executable: /bin/bash

- name: Install GitLab CE
  ansible.builtin.dnf:
    name: gitlab-ce
    state: present
  environment:
    EXTERNAL_URL: "https://{{ fqdn }}"

- name: Update root password
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "gitlab-rails runner -e production \"user = user = User.find(1); user.password = user.password_confirmation = '{{ password }}'; user.save!\""