---
- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Copy container-gitlab.service
  ansible.builtin.copy:
    src: ../files/container-gitlab.service
    dest: /etc/systemd/system/container-gitlab.service
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Replace the config container service
  ansible.builtin.replace:
    path: /etc/systemd/system/container-gitlab.service
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  loop:
   - { regex: "http_port_change", replace: "{{ http_port }}" }
   - { regex: "https_port_change", replace: "{{ https_port }}" }
   - { regex: "ssh_port_change", replace: "{{ ssh_port }}" }

- name: Create volumes paths
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    force: true
  loop:
    - "/etc/gitlab/logs"
    - "/etc/gitlab/data"
    - "/etc/gitlab/config"

- name: Restart service container-gitlab
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    daemon_reload: true
    name: container-gitlab

- name: Pause for 2 minutes for container finished startup
  ansible.builtin.pause:
    minutes: 2

- name: Update root password
  containers.podman.podman_container_exec:
    name: gitlab
    command: "gitlab-rails runner -e production \"user = user = User.find(1); user.password = user.password_confirmation = '{{ password }}'; user.save!\""